//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF354Act2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HardwareDBEntities : DbContext
    {
        public HardwareDBEntities()
            : base("name=HardwareDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<lgcustomer> lgcustomers { get; set; }
        public DbSet<lgdepartment> lgdepartments { get; set; }
        public DbSet<lgemployee> lgemployees { get; set; }
        public DbSet<lginvoice> lginvoices { get; set; }
        public DbSet<lgline> lglines { get; set; }
        public DbSet<lgproduct> lgproducts { get; set; }
        public DbSet<lgsupply> lgsupplies { get; set; }
        public DbSet<lgvendor> lgvendors { get; set; }
    }
}
